server:
  port : 8080
spring:
  application:
    name: Habitus
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PW}
    driverClassName: org.postgresql.Driver
  jpa:
    open-in-view: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.yaml
    user: ${DB_USER}
    password: ${DB_PW}