server:
  port : 8080
spring:
  application:
    name: Habitus
  datasource:
    url: ${APP_DB_URL}
    username: ${APP_DB_USER}
    password: ${APP_DB_PW}
    driverClassName: org.postgresql.Driver
  jpa:
    open-in-view: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.yaml
    user: ${APP_DB_USER}
    password: ${APP_DB_PW}
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: application
            authorization-grant-type: authorization_code
            scope: openid
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_URL}/realms/habitus
            user-name-attribute: preferred_username
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_URL}/realms/habitus


